FROM postgres:17.4
ENV TZ=America/Los_Angeles

RUN apt-get update && \
    apt-get install -y build-essential postgresql-server-dev-17 git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/pgvector/pgvector.git /tmp/pgvector && \
    cd /tmp/pgvector && \
    make && \
    make install && \
    rm -rf /tmp/pgvector

COPY 001_db_schema.sql /docker-entrypoint-initdb.d/
